### ISSUE TITLE
[proposal] Could the legend based on blue be better?

### ISSUE THREAD

**Issue by isaron** [hycomsa/hycom-c4#1]
Firstly, thanks your work for this library!

Probably it's my personal sense that the C4 legend from the [C4model website](https://c4model.com/) could be better for visual identification, which is based on blue.

What do you think?

**Comment by maciek365** [comment]
I'm very glad that you are interested in using the **Hycom C4** plugin. This library has been created for Hycom company (https://hycom.digital/ and https://hycom.pl/) and its brand colour is violet/purple, so that is why C4 elements are not blue in this library.

If you prefer the blue colour of C4 elements then you can use my alternative library published at my account: https://github.com/maciek365/c4-diagrams.net
This library contains slightly bigger blue elements instead of using Hycom's branding palette.

**Comment by isaron** [comment]
@maciek365 

Thanks your response. I'll try the EasyC4 library.
